[variables]
NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22", "yarn", "python3"]

[phases.install]
cmds = ["yarn install --immutable"]

[phases.build]
cmds = ["npx nx run-many -t build -p twenty-server twenty-front"]

[start]
cmd = "yarn start"
