version: '3.8'

services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main-app
      - twentycrm
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Main ImmigrantsRUs application
  main-app:
    build:
      context: .
      dockerfile: Dockerfile.main
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - "3001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # TwentyCRM application
  twentycrm:
    image: twentycrm/twenty:latest
    environment:
      - NODE_ENV=production
      - PORT=3002
      - SERVER_URL=${SERVER_URL}/staff-portal
      - FRONTEND_URL=${FRONTEND_URL}/staff-portal
      - PG_DATABASE_URL=${PG_DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - APP_SECRET=${APP_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - LOGIN_TOKEN_SECRET=${LOGIN_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - FILE_TOKEN_SECRET=${FILE_TOKEN_SECRET}
      - STORAGE_TYPE=local
      - DISABLE_DB_MIGRATIONS=false
      - DISABLE_CRON_JOBS_REGISTRATION=false
    expose:
      - "3002"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - twentycrm_storage:/app/storage

volumes:
  twentycrm_storage:
